version: '3.5'

services:

  simulator:
    container_name: simulator 
    build: './simulator'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    links:
      - mongodb
      - dashboard
    depends_on:
      - mongodb
      - dashboard
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # -- run quiet

  dashboard:
    container_name: "dashboard"
    build: './dashboard'
    volumes:
      - '.:/usr/src/dashboard'
      - '/usr/src/dashboard/node_modules'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    command: node index.js
